name: CI/CD Pipeline for Machine Learning Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Requirements.txt

      - name: lint model
      run: |
        python lint_model.py

    - name: Run tests
      run: |
        python test_model.py

    - name: Deploy model
      run: |
        python deploy_model.py

 
