# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python test_model.py

    - name: Train model
      run: |
        python train_model.py

    - name: Upload model artifact
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: path/to/your/model/output
