name: CI/CD Pipeline for ML Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_requirements:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change to your desired version of Python
        
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # This installs the dependencies

  lint:
    runs-on: ubuntu-latest
    needs: install_requirements  # Ensures dependencies are installed before linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies (for linting, if needed)
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linting
        run: |
          flake8 your_ml_project_directory  # Adjust with your actual project directory

  test:
    runs-on: ubuntu-latest
    needs: install_requirements  # Ensures dependencies are installed before running tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installs the dependencies from requirements.txt

      - name: Run tests with pytest
        run: |
          pytest tests/  # Ensure you have tests in the "tests/" directory

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures tests are run before deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies for deployment

      - name: Deploy model
        run: |
          echo "Deploying model..."  # Replace with your deployment command
